# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 07:03
from __future__ import unicode_literals

import aldryn_newsblog.models
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aldryn_newsblog', '0015_auto_20161208_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageAwareTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('language', models.CharField(db_index=True, editable=False, max_length=15, verbose_name='language')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_newsblog_taggedarticle_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_newsblog_taggedarticle_items', to='aldryn_newsblog.LanguageAwareTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=aldryn_newsblog.models.ArticleTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='aldryn_newsblog.TaggedArticle', to='aldryn_newsblog.LanguageAwareTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='newsblogconfig',
            name='namespace',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AlterField(
            model_name='newsblogconfig',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='languageawaretag',
            unique_together=set([('name', 'language'), ('slug', 'language')]),
        ),
    ]
